"""Agregar motivoCancelacion a Cita

Revision ID: 30241c048b4e
Revises: 94a12018b4b7
Create Date: 2025-05-13 22:37:26.461166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30241c048b4e'
down_revision: Union[str, None] = '94a12018b4b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Cita', sa.Column('motivoCancelacion', sa.NVARCHAR(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Cita', 'motivoCancelacion')
    # ### end Alembic commands ###
