"""agregar_recordatorioEnviado_a_cita

Revision ID: 94a12018b4b7
Revises: 7fd44496ef99
Create Date: 2025-05-06 21:49:04.537304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94a12018b4b7'
down_revision: Union[str, None] = '7fd44496ef99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Cita', sa.Column('recordatorioEnviado', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    op.alter_column('Cita', 'idVeterinario',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('ix_VeterinarioServicio_servicioId', table_name='VeterinarioServicio')
    op.drop_index('ix_VeterinarioServicio_veterinarioId', table_name='VeterinarioServicio')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_VeterinarioServicio_veterinarioId', 'VeterinarioServicio', ['veterinarioId'], unique=False)
    op.create_index('ix_VeterinarioServicio_servicioId', 'VeterinarioServicio', ['servicioId'], unique=False)
    op.alter_column('Cita', 'idVeterinario',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('Cita', 'recordatorioEnviado')
    # ### end Alembic commands ###
